### ISSUE TITLE
Remove Hard coding from FileProcessor code and other hard coding

### ISSUE THREAD

**Issue by susilupwork** [k8-proxy/k8-test-data#80]
please make the external endpoints configurable going forward (See the below code snippet), as it is important during K8 deployment (It is now hardcoded for testing). And there are similar places even in other modules.

    def rebuild(filename, file, mode):
        .......
        try:
            # TODO: To make this configurable, as it is imporant during Kubnernetes deployment.
            # response = requests.post("http://glasswall-rebuild:5003/process", files=files, data={'mode': mode})
            response = requests.post("http://glasswall-rebuild-svc.k8-test-data.svc.cluster.local:5003/process", files=files, data={'mode': mode})

**Comment by samarthdd** [comment]
This has been done in my branch.I am waiting to merge it to master once code is segregated
