### ISSUE TITLE
Investigate and fix- When rebuild XML states, failed, why rebuild file getting created 

### ISSUE THREAD

**Issue by susilupwork** [k8-proxy/k8-test-data#92]
For example ,  downloaded e99d886d9825a65b416909554fc0f92468f8f946.zip from unsupported file type folder in S3, Which has 

- Rebuild file 
- Rebuild XML
The rebuild XML content is 
`{
  "message": "failed"
}`
However the rebuild file got created. Investigate the issue and fix it.

**Comment by belwase** [comment]
@susilupwork  the rebuild file also looks invalid. I think the rebuild engine was not able to process it.

**Comment by belwase** [comment]
Fixed it
